---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc-app-eur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btc-app-eur
  template:
    metadata:
      labels:
        app: btc-app-eur
    spec:
      containers:
        - name: btc-app-eur
          image: samuev/fetching-btc-prices:eur-latest
          ports:
            - containerPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc-app-usdt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btc-app-usdt
  template:
    metadata:
      labels:
        app: btc-app-usdt
    spec:
      containers:
        - name: btc-app-usdt
          image: samuev/fetching-btc-prices:usdt-latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: btc-app-eur
spec:
  selector:
    app: btc-app-eur
  ports:
    - protocol: TCP
      port: 81
      targetPort: 5001
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: btc-app-usdt
spec:
  selector:
    app: btc-app-usdt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
